### ISSUE TITLE
Inconsistent available votes info in voting overview

### ISSUE THREAD

**Issue by mathudak** [SophiaTX/Wallet-Frontend-issues#1]
**Describe the bug**
There is a difference between actual available votes (60) and the information in the text below (51).

**To Reproduce**
1. Go to 'https://wallet.sophiatx.com/{valid_user}/voting'
2. See error on the left side of the screen:
   Available Votes 57/ 60 
   You can vote for 0 to 51 witnesses...

**Expected behavior**
Number of available votes should be same in the text and counter.

**Screenshots**
Attached
![screenshot 2018-11-28 at 10 46 39](https://user-images.githubusercontent.com/6408246/49143468-5e715980-f2fb-11e8-9248-0e99b9281668.png)

**Desktop (please complete the following information):**
 - OS: OS X, Win 10...
 - Browser: Firefox, all available

**Smartphone (please complete the following information):**
 - Device: all

**Comment by mathudak** [comment]
Thanks @mathudak, you rock! I declare this issue as fixed and it will be deployed in next minor release

**Comment by Firexsprit** [comment]
So you increased the number of possible votes to 60 now?

**Comment by mathudak** [comment]
Kind of. There was a little misunderstanding between FE and BE teams. Number of active witnesses at once is indeed 51 but you can vote for 60 witnesses. It was possible to vote for 60 witnesses using CLI wallet not on the FE because of limiter we used. 
Once we realized our mistake we updated value in the vote counter bot forgot to change the number in the short note about voting.

**Comment by Firexsprit** [comment]
Did you choose 60 votes for a reason? I saw that active witness #52 is also building blocks and getting rewards. Is there an incentive for the witnesses 52-60 to compete with the top 51 and get at least a small reward (incentive) in order to do so?

**Comment by mathudak** [comment]
As far as I know there is such race but that's also a point from which I won't be able to answer more questions as it is far beyond my knowledge of our BC architecture. Try asking in Technical tread, you should get much better answers there.

**Comment by Firexsprit** [comment]
Asked a while ago, didn't receive an answer. A lot gets overlooked there.

**Comment by MatusKysel** [comment]
> Asked a while ago, didn't receive an answer. A lot gets overlooked there.

There will be a blog explaining why do we have those number and how exactly it is working, but I guess it will not be published this year, more likely beginning of next year.
