### ISSUE TITLE
Language improvements for "Deutsch"

### ISSUE THREAD

**Issue by Firexsprit** [SophiaTX/Wallet-Frontend-issues#2]
The -> sign points to my corrected version of the respective text/fragment displayed in bold

Title page of https://wallet.sophiatx.com/:

"Willkommen im SophiaTX Wallet" -> "**Willkommen in der SophiaTX Wallet**" #the consensus for the case for "Wallet" in German is female so the correction would sound most natural

"Treten Sie SophiaTX heute bei" -> "**Treten Sie SophiaTX noch heute bei**"

Haftungsausschluss:

"wallet.sophiatx.com ist kein "Web Wallet", sondern eine grafische Benutzeroberfläche die es erlaubt mit der SophiaTX Blockchain zu interagieren. Durch Nutzung der Wallet stellen Sie SophiaTX weder Ihre Tokens noch andere private Informationen zur Verfügung. Ihr privater Schlüssel verlässt zu keiner Zeit Ihren Computer / Browser."
-> "**wallet.sophiatx.com ist keine "Web Wallet", sondern eine grafische Benutzeroberfläche die es erlaubt mit der SophiaTX Blockchain zu interagieren. Durch Nutzung der Wallet stellen Sie SophiaTX weder Ihre Tokens noch andere private Informationen zur Verfügung. Ihr privater Schlüssel verlässt zu keiner Zeit Ihren Computer / Browser.**"

Tab "Wahl der Witness-Noden":

"Sie können für 0 bis 51 Witness-Noden stimmen. Jeder gewählte Witness-Node bekommt die volle, Ihrem Stimmgewicht entsprechende Anzahl an Stimmen."
-> "**Sie können für bis zu 51 Witness-Noden stimmen. Jede gewählte Witness-Node bekommt die volle, Ihrem Stimmgewicht entsprechende Anzahl an Stimmen.**"

Table headline:

"Meine Abstimmungen" -> "**Abgestimmt für**"
"Witness-Node"
"Link"
"Jetzt abstimmen" -> "**Stimmen**"
"Blockgröße"
"Verpasste Blocks"
"Version"

**Comment by mathudak** [comment]
Thank you @Firexsprit for your input. We've double-checked it and all the changes would be implemented in the next minor release.

**Comment by mathudak** [comment]
Fixed and deployed -> version 1.2.1
